### ISSUE TITLE
apclient_connect_update missing arguments in gml

### ISSUE THREAD

**Issue by LeonarthCG** [black-sliver/gm-apclientpp#3]
apclient_connect_update's external_define and wrapper list 0 arguments:
https://github.com/black-sliver/gm-apclientpp/blob/49af406c60e16d90d59e64a796163a86b4df9f05/gml/ap_init.gml#L57
https://github.com/black-sliver/gm-apclientpp/blob/49af406c60e16d90d59e64a796163a86b4df9f05/gml/apclient_wrappers.gml#L127

Even though it takes 1, as seen here:
https://github.com/black-sliver/gm-apclientpp/blob/49af406c60e16d90d59e64a796163a86b4df9f05/src/gm-apclientpp.cpp#L559

Is there a reason for this? I double-checked all of the other external calls, but none of them have a discrepancy like this.
In my testing the call seemed to always fail until I changed the mentioned lines.

**Comment by black-sliver** [comment]
Probably a typo by the author (ThatOneGuy27). If you can fix and test this, PRs welcome :-)
